### ISSUE TITLE
Crash when LCS is not accessible

### ISSUE THREAD

**Issue by artemt1** [microsoft/2LCS#45]
LCS had access issues today and yesterday. 2LCS crashes when I try to get a list of VMs for a given LCS project.

Call stack:
Application: 2LCS.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(System.Object, System.Type, System.Type)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(System.Object, System.Globalization.CultureInfo, System.Type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(Newtonsoft.Json.JsonReader, System.Object, System.Globalization.CultureInfo, Newtonsoft.Json.Serialization.JsonContract, System.Type)

Exception Info: Newtonsoft.Json.JsonSerializationException
   at LCS.Program.Application_ThreadException(System.Object, System.Threading.ThreadExceptionEventArgs)
   at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)
   at System.Windows.Forms.Control.WndProcException(System.Exception)
   at System.Windows.Forms.Control+ControlNativeWindow.OnThreadException(System.Exception)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at LCS.Program.Main()

Faulting application name: 2LCS.exe, version: 0.27.0.0, time stamp: 0x5e16f1e2
Faulting module name: KERNELBASE.dll, version: 10.0.18362.628, time stamp: 0x54734dee
Exception code: 0xe0434352
Fault offset: 0x00113db2
Faulting process ID: 0x7cb0
Faulting application start time: 0x01d5f778481c6cdf
Faulting application path: C:\Users\Artem\Downloads\2LCS-0.27.0.0\2LCS.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: e4948eae-d9a5-4813-87eb-1d5b70eeeb0d
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket 1668366711294004334, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: 2LCS.exe
P2: 0.27.0.0
P3: 5e16f1e2
P4: Newtonsoft.Json
P5: 12.0.3.23909
P6: dff1c7f1
P7: 473
P8: 66
P9: WQSSHWZPAYQ1I1N24AD0E43DDTRID103
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER330F.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3542.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER35A1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER359F.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER35FE.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_2LCS.exe_138249a119f2ae1f6f798940f4686e10373311d3_3c158475_b715968b-6c5b-47b8-81ee-6ad1695709be

Analysis symbol: 
Rechecking for solution: 0
Report Id: f7105aad-2874-4279-ba74-2162afc0dfa3
Report Status: 268435456
Hashed bucket: 8837ad6c728ac95e87273aaf3dc40c6e
Cab Guid: 0

**Comment by Sigvelli** [comment]
I also experienced several similar crashes of 2LCS. When I disabled "Auto-refresh list of instances after switching projects", 2LCS works ok.
The message in Lifecycle Service 10-11 of March is: "LCS is experiencing an outage which is causing all environment details in LCS to not be accessible."

**Comment by TomekMelissa** [comment]
fixed in 0.28.0
